name: My first workflow
on:
  push:
    paths:
      - 'notebooks/**'
    tags:
      - 'prod'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Changed Files
        id: changed-files
          with:
            files: |
              notebooks/**

      - name: Run python script
        if: steps.changed-files.outputs.any_changed == 'true'
        run: python ./python_scripts/sample_python.py "${{ steps.changed-files.outputs.all_changed_files }}"
