name: My first workflow
on:
  push:
    paths:
      - 'notebooks/**'
    tags:
      - 'prod'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v34

      - name: Get Changed Files
        id:  changed-files-specific
          uses: tj-actions/changed-files@v34
          with:
            files: |
              notebooks/**

      - name: Run python script
        if: steps. changed-files-specific.outputs.any_changed == 'true'
        run: python ./python_scripts/sample_python.py "${{ steps. changed-files-specific.outputs.all_changed_files }}"
