name: My first workflow
on:
  push:
    paths:
      - 'notebooks/**'
    tags:
      - 'prod'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: python ./python_scripts/sample_python.py "${{paths}}"
