name: My first workflow
author: camille2985@berkeley.edu
description: this is my attempt to learn how to make github actions
inputs:
  production_ready:
    description: 'Is this this code ready for production?'
    required: false
    default: false
  message:
    description: 'What do should this script say to you'
    required: true
    default: 'Hello Camille Church'
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: python ./python_scripts/sample_python.py "${{inputs.message}}"
